refactor: add check for existence of dist and types directories before npm publish

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -42,6 +42,16 @@ jobs:
           registry-url: https://registry.npmjs.org/
       - run: yarn install
       - run: yarn build
+      - name: Check if dist and types directories exist
+        run: |
+          if [ ! -d "dist" ]; then
+        echo "Error: dist directory does not exist."
+        exit 1
+          fi
+          if [ ! -d "types" ]; then
+        echo "Error: types directory does not exist."
+        exit 1
+          fi
       - run: npm publish
         env:
           NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
